package test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeCoverableFixture(t *testing.T, files map[string]string) string {
	t.Helper()
	dir := t.TempDir()
	for name, content := range files {
		path := filepath.Join(dir, name)
		require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o755))

		require.NoError(t, os.WriteFile(path, []byte(content), 0o644))

	}
	return dir
}

func TestHasCoverableStatements(t *testing.T) {
	t.Serial()
	for _, tc := range []struct {
		name  string
		files map[string]string
		want  bool
	}{
		{"embed-only module", map[string]string{
			"go.mod":   "module example.com/web\n\ngo 1.21\n",
			"embed.go": "package web\n\nimport \"embed\"\n\n//go:embed src\nvar Src embed.FS\n",
			"src/x.ts": "// not go\n",
		}, false},
		{"function with statements", map[string]string{
			"go.mod":  "module example.com/pkg\n\ngo 1.21\n",
			"main.go": "package main\n\nfunc main() { println(\"hi\") }\n",
		}, true},
		{"function literal in package-level var", map[string]string{
			"go.mod": "module example.com/pkg\n\ngo 1.21\n",
			"fn.go":  "package pkg\n\nvar F = func() int { return 1 }\n",
		}, true},
		{"empty function bodies only", map[string]string{
			"go.mod":  "module example.com/pkg\n\ngo 1.21\n",
			"noop.go": "package pkg\n\nfunc Noop() {}\n",
		}, false},
		{"statements only in tests", map[string]string{
			"go.mod":    "module example.com/pkg\n\ngo 1.21\n",
			"decls.go":  "package pkg\n\nconst X = 1\n",
			"x_test.go": "package pkg\n\nimport \"testing\"\n\nfunc TestX(t *testing.T) { _ = X }\n",
		}, false},
		{"statements only in generated file", map[string]string{
			"go.mod": "module example.com/pkg\n\ngo 1.21\n",
			"gen.go": "// Code generated by mockgen. DO NOT EDIT.\n\npackage pkg\n\nfunc Gen() { println(\"g\") }\n",
		}, false},
		{"statements only in build-ignored file", map[string]string{
			"go.mod":   "module example.com/pkg\n\ngo 1.21\n",
			"tool.go":  "//go:build ignore\n\npackage main\n\nfunc main() { println(\"gen\") }\n",
			"decls.go": "package pkg\n\nvar X = 1\n",
		}, false},
		{"statements only in nested module", map[string]string{
			"go.mod":           "module example.com/pkg\n\ngo 1.21\n",
			"decls.go":         "package pkg\n\nvar X = 1\n",
			"compat/go.mod":    "module example.com/compat\n\ngo 1.21\n",
			"compat/compat.go": "package compat\n\nfunc C() { println(\"c\") }\n",
		}, false},
		{"statements only under vendor", map[string]string{
			"go.mod":        "module example.com/pkg\n\ngo 1.21\n",
			"decls.go":      "package pkg\n\nvar X = 1\n",
			"vendor/v/v.go": "package v\n\nfunc V() { println(\"v\") }\n",
		}, false},
		{"statements in subdirectory package", map[string]string{
			"go.mod":      "module example.com/pkg\n\ngo 1.21\n",
			"decls.go":    "package pkg\n\nvar X = 1\n",
			"sub/sub.go":  "package sub\n\nfunc S() { println(\"s\") }\n",
			"sub/util.ts": "// not go\n",
		}, true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			assert.Equal(t, tc.want, HasCoverableStatements(writeCoverableFixture(t, tc.files)))
		})
	}
}

func TestFileHasFuncBodyUnparseable(t *testing.T) {
	t.Serial()
	dir := t.TempDir()
	bad := filepath.Join(dir, "bad.go")
	os.WriteFile(bad, []byte("package \x00 not go"), 0o644)
	assert.False(t, fileHasFuncBody(bad))
	assert.False(t, fileHasFuncBody(filepath.Join(dir, "missing.go")))
}
