package test

import (
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func TestParseProfile(t *testing.T) {
	tmpDir := t.TempDir()
	coverFile := filepath.Join(tmpDir, "coverage.out")

	// Build test data with known coverage:
	// file1: 2 statements, 1 covered (50%)
	// file2: 2 statements, 2 covered (100%)
	// total: 4 statements, 3 covered (75%)
	lines := []struct {
		file       string
		statements int
		covered    bool
	}{
		{"example.com/pkg/file1.go:10.20,12.2", 1, true},
		{"example.com/pkg/file1.go:14.20,16.2", 1, false},
		{"example.com/pkg/file2.go:10.20,12.2", 1, true},
		{"example.com/pkg/file2.go:14.20,16.2", 1, true},
	}

	var totalStmts, coveredStmts int
	content := "mode: set\n"
	for _, l := range lines {
		count := 0
		if l.covered {
			count = 1
			coveredStmts += l.statements
		}
		totalStmts += l.statements
		content += fmt.Sprintf("%s %d %d\n", l.file, l.statements, count)
	}

	expectedTotal := float32(coveredStmts) / float32(totalStmts) * 100

	if err := os.WriteFile(coverFile, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write coverage file: %v", err)
	}

	total, files, err := ParseProfile(coverFile)
	if err != nil {
		t.Fatalf("ParseProfile failed: %v", err)
	}

	if total != expectedTotal {
		t.Errorf("expected total coverage %.1f%%, got %.1f%%", expectedTotal, total)
	}

	if len(files) != 2 {
		t.Errorf("expected 2 files, got %d", len(files))
	}
}

func TestParseProfileMissingFile(t *testing.T) {
	_, _, err := ParseProfile("/nonexistent/coverage.out")
	if err == nil {
		t.Error("expected error for missing file")
	}
}

func TestParseProfileEmpty(t *testing.T) {
	tmpDir := t.TempDir()
	coverFile := filepath.Join(tmpDir, "coverage.out")

	content := `mode: set
`
	if err := os.WriteFile(coverFile, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write coverage file: %v", err)
	}

	total, files, err := ParseProfile(coverFile)
	if err != nil {
		t.Fatalf("ParseProfile failed: %v", err)
	}

	if total != 0 {
		t.Errorf("expected 0%% coverage for empty profile, got %.1f%%", total)
	}

	if len(files) != 0 {
		t.Errorf("expected 0 files, got %d", len(files))
	}
}

func TestParseProfileMalformedLines(t *testing.T) {
	tmpDir := t.TempDir()
	coverFile := filepath.Join(tmpDir, "coverage.out")

	// Various malformed lines that should be skipped
	content := `mode: set
not enough fields
too many fields here now extra
no-colon-in-path 1 1
example.com/pkg/file.go:10.20,12.2 1 1
`
	if err := os.WriteFile(coverFile, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write coverage file: %v", err)
	}

	total, files, err := ParseProfile(coverFile)
	if err != nil {
		t.Fatalf("ParseProfile failed: %v", err)
	}

	// Should only have parsed the valid line
	if len(files) != 1 {
		t.Errorf("expected 1 file, got %d", len(files))
	}
	if total != 100 {
		t.Errorf("expected 100%% coverage, got %.1f%%", total)
	}
}

func TestParseFuncCoverageMissingFile(t *testing.T) {
	_, err := ParseFuncCoverage("/nonexistent/coverage.out")
	if err == nil {
		t.Error("expected error for missing file")
	}
}

func TestParseFuncCoverageWithRealFile(t *testing.T) {
	// Use the coverage.out generated by running tests
	if _, err := os.Stat("coverage.out"); os.IsNotExist(err) {
		t.Skip("coverage.out not found, skipping")
	}

	funcs, err := ParseFuncCoverage("coverage.out")
	if err != nil {
		t.Fatalf("ParseFuncCoverage failed: %v", err)
	}

	// May return empty if go tool cover can't find sources (e.g., during test)
	// Verify structure of any returned data
	for _, f := range funcs {
		if f.File == "" {
			t.Error("function has empty file path")
		}
		if f.Function == "" {
			t.Error("function has empty function name")
		}
		if f.Coverage < 0 || f.Coverage > 100 {
			t.Errorf("function %s has invalid coverage: %v", f.Function, f.Coverage)
		}
	}
}

func TestParseFuncCoverageOutput(t *testing.T) {
	// Format matches `go tool cover -func` output: file:line:\tfunc\tcoverage%
	output := `example.com/pkg/main.go:10:		main		0.0%
example.com/pkg/main.go:20:		helper		100.0%
example.com/pkg/util.go:5:		parse		75.5%
total:						(statements)	58.5%
`
	funcs := parseFuncCoverageOutput(output)

	if len(funcs) != 3 {
		t.Fatalf("expected 3 functions, got %d", len(funcs))
	}

	// Check first function
	if funcs[0].File != "example.com/pkg/main.go" {
		t.Errorf("expected file 'example.com/pkg/main.go', got %q", funcs[0].File)
	}
	if funcs[0].Line != 10 {
		t.Errorf("expected line 10, got %d", funcs[0].Line)
	}
	if funcs[0].Function != "main" {
		t.Errorf("expected function 'main', got %q", funcs[0].Function)
	}
	if funcs[0].Coverage != 0.0 {
		t.Errorf("expected coverage 0.0, got %v", funcs[0].Coverage)
	}

	// Check second function
	if funcs[1].Coverage != 100.0 {
		t.Errorf("expected coverage 100.0, got %v", funcs[1].Coverage)
	}

	// Check third function
	if funcs[2].Coverage != 75.5 {
		t.Errorf("expected coverage 75.5, got %v", funcs[2].Coverage)
	}
}

func TestParseFuncCoverageOutputEmpty(t *testing.T) {
	funcs := parseFuncCoverageOutput("")
	if len(funcs) != 0 {
		t.Errorf("expected 0 functions for empty output, got %d", len(funcs))
	}
}

func TestParseFuncCoverageOutputMalformed(t *testing.T) {
	output := `not enough fields
no-colon 50.0%
total:					(statements)	100.0%
`
	funcs := parseFuncCoverageOutput(output)
	if len(funcs) != 0 {
		t.Errorf("expected 0 functions for malformed output, got %d", len(funcs))
	}
}
