package test

import (
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"os"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFile(t *testing.T) {
	dir := t.TempDir()

	tests := []struct {
		name    string
		content string
		want    bool
	}{
		{
			name: "sqlc generated",
			content: `// Code generated by sqlc. DO NOT EDIT.

package db
`,
			want: true,
		},
		{
			name: "protobuf generated",
			content: `// Code generated by protoc-gen-go. DO NOT EDIT.

package pb
`,
			want: true,
		},
		{
			name: "normal file",
			content: `package main

func main() {}
`,
			want: false,
		},
		{
			name: "comment after package clause",
			content: `package main

// Code generated by foo. DO NOT EDIT.
`,
			want: false,
		},
		{
			name: "marker with build tag",
			content: `//go:build linux

// Code generated by mockgen. DO NOT EDIT.

package mock
`,
			want: true,
		},
		{
			name:    "empty file",
			content: "",
			want:    false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			path := filepath.Join(dir, tt.name+".go")
			require.NoError(t, os.WriteFile(path, []byte(tt.content), 0644))

			got := isGeneratedFile(path)
			assert.Equal(t, tt.want, got)

		})
	}
}

func TestIsGeneratedPackage(t *testing.T) {
	t.Run("all generated", func(t *testing.T) {
		dir := t.TempDir()
		writeFile(t, dir, "models.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
		writeFile(t, dir, "querier.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
		assert.True(t, isGeneratedPackage(dir))

	})

	t.Run("mixed", func(t *testing.T) {
		dir := t.TempDir()
		writeFile(t, dir, "models.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
		writeFile(t, dir, "helpers.go", "package db\n\nfunc Helper() {}\n")
		assert.False(t, isGeneratedPackage(dir))

	})

	t.Run("test files ignored", func(t *testing.T) {
		dir := t.TempDir()
		writeFile(t, dir, "models.go", "// Code generated by sqlc. DO NOT EDIT.\n\npackage db\n")
		writeFile(t, dir, "models_test.go", "package db\n\nimport \"testing\"\nfunc TestModels(t *testing.T) {}\n")
		assert.True(t, isGeneratedPackage(dir))

	})

	t.Run("no go files", func(t *testing.T) {
		dir := t.TempDir()
		writeFile(t, dir, "README.md", "# hello\n")
		assert.False(t, isGeneratedPackage(dir))

	})
}

func writeFile(t *testing.T, dir, name, content string) {
	t.Helper()
	require.NoError(t, os.WriteFile(filepath.Join(dir, name), []byte(content), 0644))

}
