name: 'Go Safe Build'
description: 'Build Go projects with coverage enforcement - fails if coverage is below threshold'
author: 'go-toolchain'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  min-coverage:
    description: 'Minimum coverage percentage required (0 = test only, no build)'
    required: false
    default: '80'
  cov-detail:
    description: 'Show detailed coverage: "func" or "file"'
    required: false
    default: ''
  json:
    description: 'Output coverage report as JSON'
    required: false
    default: 'false'
  verbose:
    description: 'Show test output line by line'
    required: false
    default: 'false'
  working-directory:
    description: 'Working directory for the build'
    required: false
    default: '.'

outputs:
  coverage:
    description: 'Total coverage percentage'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Run go-toolchain
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail
        ARGS="--min-coverage ${{ inputs.min-coverage }}"
        if [ -n "${{ inputs.cov-detail }}" ]; then
          ARGS="$ARGS --cov-detail ${{ inputs.cov-detail }}"
        fi
        if [ "${{ inputs.json }}" = "true" ]; then
          ARGS="$ARGS --json"
        fi
        if [ "${{ inputs.verbose }}" = "true" ]; then
          ARGS="$ARGS --verbose"
        fi
        # Self-test: use commit SHA when running in this repo
        if [ "$GITHUB_REPOSITORY" = "wow-look-at-my/go-toolchain" ]; then
          go run github.com/wow-look-at-my/go-toolchain/src@$GITHUB_SHA matrix $ARGS
        else
          go run github.com/wow-look-at-my/go-toolchain/src@latest matrix $ARGS
        fi
