name: 'Go Safe Build'
description: 'Build Go projects with coverage enforcement - fails if coverage is below threshold'
author: 'go-toolchain'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  json:
    description: 'Output coverage report as JSON'
    required: false
    default: 'false'
  verbose:
    description: 'Show test output line by line'
    required: false
    default: 'false'
  generate:
    description: 'Run go:generate directives matching this hash'
    required: false
    default: ''
  working-directory:
    description: 'Working directory for the build'
    required: false
    default: '.'
  go-version:
    description: 'Go version to install (e.g. 1.25). Overrides go-version-file.'
    required: false
    default: ''
  go-version-file:
    description: 'Path to go.mod to read Go version from'
    required: false
    default: './go.mod'

outputs:
  coverage:
    description: 'Total coverage percentage'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.go-version }}
        go-version-file: ${{ inputs.go-version-file }}
        cache: true

    - name: Run go-toolchain
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GOPROXY: direct
        GOSUMDB: 'off'
        GONOSUMCHECK: '*'
      run: |
        set -euo pipefail
        ARGS=""
        if [ "${{ inputs.json }}" = "true" ]; then
          ARGS="$ARGS --json"
        fi
        if [ "${{ inputs.verbose }}" = "true" ]; then
          ARGS="$ARGS --verbose"
        fi
        if [ -n "${{ inputs.generate }}" ]; then
          ARGS="$ARGS --generate ${{ inputs.generate }}"
        fi
        # Self-test: use local source (go.mod has replace directives)
        if [ "$GITHUB_REPOSITORY" = "wow-look-at-my/go-toolchain" ]; then
          go run ./src matrix $ARGS
        else
          go run github.com/wow-look-at-my/go-toolchain@latest matrix $ARGS
        fi
