package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/wow-look-at-my/testify/assert"
	"github.com/wow-look-at-my/testify/require"
)

func TestCheckFileLength_UnderThreshold(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "short.go"), []byte("package foo\n\nfunc Foo() {}\n"), 0644)

	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_Warning(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthWarn; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "medium.go"), []byte(sb.String()), 0644)

	// Warning only, no error
	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_Error(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "long.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "exceed")
}

func TestCheckFileLength_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("// Code generated by foo; DO NOT EDIT.\n")
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError+100; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "generated.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_SkipsVendor(t *testing.T) {
	dir := t.TempDir()
	vendorDir := filepath.Join(dir, "vendor", "pkg")
	os.MkdirAll(vendorDir, 0755)

	var sb strings.Builder
	sb.WriteString("package pkg\n\n")
	for i := 0; i < fileLengthError+100; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(vendorDir, "big.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_TestFile(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "foo_test.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "exceed")
}
