package cmd

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestCheckFileLength_UnderThreshold(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "short.go"), []byte("package foo\n\nfunc Foo() {}\n"), 0644)

	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_Warning(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthWarn; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "medium.go"), []byte(sb.String()), 0644)

	// Warning only, no error
	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_Error(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "long.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "exceed")
}

func TestIsGeneratedFile(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "header marker",
			src:  "// Code generated by foo. DO NOT EDIT.\npackage foo\n",
			want: true,
		},
		{
			name: "marker below package",
			src:  "package foo\n\n// Code generated by foo. DO NOT EDIT.\nvar x = 1\n",
			want: false,
		},
		{
			name: "no marker",
			src:  "package foo\n\nfunc Foo() {}\n",
			want: false,
		},
		{
			name: "after build constraint block",
			src:  "//go:build linux\n// +build linux\n\n// Code generated by foo. DO NOT EDIT.\npackage foo\n",
			want: true,
		},
		{
			name: "crlf line endings",
			src:  "// Code generated by foo. DO NOT EDIT.\r\npackage foo\r\n",
			want: true,
		},
		{
			name: "no trailing newline",
			src:  "// Code generated by foo. DO NOT EDIT.",
			want: true,
		},
		{
			name: "lowercase marker",
			src:  "// code generated by foo. DO NOT EDIT.\npackage foo\n",
			want: false,
		},
		{
			name: "missing trailing period",
			src:  "// Code generated by foo. DO NOT EDIT\npackage foo\n",
			want: false,
		},
		{
			name: "trailing content after period",
			src:  "// Code generated by foo. DO NOT EDIT. really\npackage foo\n",
			want: false,
		},
		{
			name: "block comment before marker",
			src:  "/* copyright header */\n// Code generated by foo. DO NOT EDIT.\npackage foo\n",
			want: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got := isGeneratedFile(strings.NewReader(tc.src))
			assert.Equal(t, tc.want, got)
		})
	}
}

func TestCheckFileLength_SkipsGenerated(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("// Code generated by foo. DO NOT EDIT.\n")
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError+100; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "generated.go"), []byte(sb.String()), 0644)

	t.Setenv("GITHUB_ACTIONS", "true")

	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	err := checkFileLength(dir)

	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	buf.ReadFrom(r)
	output := buf.String()

	assert.NoError(t, err)
	// No warning or error annotation for the (large) generated file.
	assert.NotContains(t, output, "::warning")
	assert.NotContains(t, output, "::error")
	// The skip notice is printed.
	assert.Contains(t, output, "File length check: skipped 1 generated file(s)")
}

func TestCheckFileLength_NoSkipNoticeWhenNothingSkipped(t *testing.T) {
	dir := t.TempDir()
	os.WriteFile(filepath.Join(dir, "short.go"), []byte("package foo\n\nfunc Foo() {}\n"), 0644)

	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	err := checkFileLength(dir)

	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	buf.ReadFrom(r)
	output := buf.String()

	assert.NoError(t, err)
	assert.NotContains(t, output, "skipped")
}

func TestCheckFileLength_CountGeneratedFailsLargeGenerated(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("// Code generated by foo. DO NOT EDIT.\n")
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "generated.go"), []byte(sb.String()), 0644)

	countGenerated = true
	defer func() { countGenerated = false }()

	err := checkFileLength(dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "exceed")
}

func TestCheckFileLength_SkipsVendor(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	vendorDir := filepath.Join(dir, "vendor", "pkg")
	os.MkdirAll(vendorDir, 0755)

	var sb strings.Builder
	sb.WriteString("package pkg\n\n")
	for i := 0; i < fileLengthError+100; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(vendorDir, "big.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	assert.NoError(t, err)
}

func TestCheckFileLength_GHAWarningAnnotation(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthWarn; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "medium.go"), []byte(sb.String()), 0644)

	t.Setenv("GITHUB_ACTIONS", "true")

	// Capture stdout
	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	err := checkFileLength(dir)

	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	buf.ReadFrom(r)
	output := buf.String()

	assert.NoError(t, err)
	assert.Contains(t, output, "::warning file=")
	assert.NotContains(t, output, "::error")
}

func TestCheckFileLength_GHAErrorAnnotation(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "long.go"), []byte(sb.String()), 0644)

	t.Setenv("GITHUB_ACTIONS", "true")

	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	err := checkFileLength(dir)

	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	buf.ReadFrom(r)
	output := buf.String()

	require.Error(t, err)
	assert.Contains(t, output, "::error file=")
	assert.NotContains(t, output, "::warning")
}

func TestCheckFileLength_NoGHAAnnotationsLocally(t *testing.T) {
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthWarn; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "medium.go"), []byte(sb.String()), 0644)

	t.Setenv("GITHUB_ACTIONS", "")

	old := os.Stdout
	r, w, _ := os.Pipe()
	os.Stdout = w

	err := checkFileLength(dir)

	w.Close()
	os.Stdout = old
	var buf bytes.Buffer
	buf.ReadFrom(r)
	output := buf.String()

	assert.NoError(t, err)
	assert.NotContains(t, output, "::warning")
	assert.NotContains(t, output, "::error")
}

func TestCheckFileLength_TestFile(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()

	var sb strings.Builder
	sb.WriteString("package foo\n\n")
	for i := 0; i < fileLengthError; i++ {
		fmt.Fprintf(&sb, "var x%d = %d\n", i, i)
	}
	os.WriteFile(filepath.Join(dir, "foo_test.go"), []byte(sb.String()), 0644)

	err := checkFileLength(dir)
	require.Error(t, err)
	assert.Contains(t, err.Error(), "exceed")
}
