package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// distHeader opens every file cmd/dist generates.
const distHeader = "// Code generated by go tool dist; DO NOT EDIT.\n\n"

// distFile is a source file cmd/dist writes into the tree and git ignores,
// which a pristine checkout therefore lacks.
type distFile struct {
	path string
	body func(goroot string) (string, error)
}

// distFiles are the files cmd/dist generates, with the defaults it takes
// when no environment variable names another value.
var distFiles = []distFile{
	{"src/internal/runtime/sys/zversion.go", func(string) (string, error) { return "package sys\n", nil }},
	{"src/internal/buildcfg/zbootstrap.go", buildcfgBody},
	{"src/cmd/go/internal/cfg/zdefaultcc.go", func(string) (string, error) { return defaultCCBody("cfg", "DefaultPkgConfig", "DefaultCC", "DefaultCXX"), nil }},
	{"src/cmd/cgo/zdefaultcc.go", func(string) (string, error) { return defaultCCBody("cgo", "defaultPkgConfig", "defaultCC", "defaultCXX"), nil }},
	{"src/time/tzdata/zzipdata.go", tzdataBody},
}

// generateForkFiles writes the generated sources a checkout of the fork
// needs before its standard library and toolchain compile, leaving a file
// that already holds the same bytes alone.
func generateForkFiles(goroot string) error {
	for _, file := range distFiles {
		body, err := file.body(goroot)
		if err != nil {
			return err
		}
		content := distHeader + body
		path := filepath.Join(goroot, filepath.FromSlash(file.path))
		if have, err := os.ReadFile(path); err == nil && string(have) == content {
			continue
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return fmt.Errorf("writing %s: %w", file.path, err)
		}
	}
	return nil
}

// forkVersion is the first line of the checkout's VERSION file.
func forkVersion(goroot string) (string, error) {
	data, err := os.ReadFile(filepath.Join(goroot, "VERSION"))
	if err != nil {
		return "", fmt.Errorf("reading the fork's VERSION: %w", err)
	}
	version, _, _ := strings.Cut(string(data), "\n")
	return strings.TrimSpace(version), nil
}

// buildcfgBody is internal/buildcfg/zbootstrap.go as cmd/dist writes it with
// every knob at its default: the cosmo default GOOS and the host's GOARCH.
func buildcfgBody(goroot string) (string, error) {
	version, err := forkVersion(goroot)
	if err != nil {
		return "", err
	}
	var buf strings.Builder
	buf.WriteString("package buildcfg\n\nimport \"runtime\"\n\n")
	for _, line := range []string{
		"const DefaultGO386 = `sse2`",
		"const DefaultGOAMD64 = `v1`",
		"const DefaultGOARM = `7`",
		"const DefaultGOARM64 = `v8.0`",
		"const DefaultGOMIPS = `hardfloat`",
		"const DefaultGOMIPS64 = `hardfloat`",
		"const DefaultGOPPC64 = `power8`",
		"const DefaultGORISCV64 = `rva20u64`",
		"const defaultGOEXPERIMENT = ``",
		"const defaultGO_EXTLINK_ENABLED = ``",
		"const defaultGO_LDSO = ``",
		"const version = `" + version + "`",
		"const defaultGOOS = `cosmo`",
		"var defaultGOARCH = runtime.GOARCH",
		"const DefaultGOFIPS140 = `off`",
		"const DefaultCGO_ENABLED = \"\"",
	} {
		buf.WriteString(line + "\n")
	}
	return buf.String(), nil
}

// defaultCCBody is a zdefaultcc.go: the C compilers cmd/dist picks per
// GOOS when no CC is configured.
func defaultCCBody(pkg, pkgConfig, ccName, cxxName string) string {
	var buf strings.Builder
	fmt.Fprintf(&buf, "package %s\n\n", pkg)
	fmt.Fprintf(&buf, "const %s = `pkg-config`\n", pkgConfig)
	buf.WriteString(defaultCCFunc(ccName, "clang", "gcc"))
	buf.WriteString(defaultCCFunc(cxxName, "clang++", "g++"))
	return buf.String()
}

// defaultCCFunc is one compiler-picking function of a zdefaultcc.go.
func defaultCCFunc(name, clang, gcc string) string {
	var buf strings.Builder
	fmt.Fprintf(&buf, "func %s(goos, goarch string) string {\n", name)
	buf.WriteString("\tswitch goos+`/`+goarch {\n\t}\n")
	buf.WriteString("\tswitch goos {\n")
	fmt.Fprintf(&buf, "\tcase \"darwin\", \"ios\", \"freebsd\", \"openbsd\":\n\t\treturn %q\n\t}\n", clang)
	fmt.Fprintf(&buf, "\treturn %q\n}\n", gcc)
	return buf.String()
}

// tzdataBody is time/tzdata/zzipdata.go: the zoneinfo zip as a string,
// spelled with hex escapes so the bootstrap Go's quoting never enters.
func tzdataBody(goroot string) (string, error) {
	zip, err := os.ReadFile(filepath.Join(goroot, "lib", "time", "zoneinfo.zip"))
	if err != nil {
		return "", fmt.Errorf("reading the fork's zoneinfo.zip: %w", err)
	}
	return "package tzdata\n\nconst zipdata = " + distQuote(zip) + "\n", nil
}

// distQuote quotes bytes the way cmd/dist does: printable ASCII as itself,
// everything else as a hex escape.
func distQuote(data []byte) string {
	const hex = "0123456789abcdef"
	var out strings.Builder
	out.WriteByte('"')
	for _, char := range data {
		if 0x20 <= char && char <= 0x7E && char != '"' && char != '\\' {
			out.WriteByte(char)
			continue
		}
		out.WriteByte('\\')
		out.WriteByte('x')
		out.WriteByte(hex[char>>4])
		out.WriteByte(hex[char&0xf])
	}
	out.WriteByte('"')
	return out.String()
}
