package vet

import (
	"go/ast"
	"go/parser"
	"go/token"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"github.com/wow-look-at-my/go-toolchain/src/logger"
	"golang.org/x/tools/go/analysis"
)

// TestCommentNumbersReadsACount pins what the check calls a number: digits
// standing alone, digits wearing an ordinal suffix, and a number spelled out.
func TestCommentNumbersReadsACount(t *testing.T) {
	for _, c := range []struct {
		name string
		text string
		want string
	}{
		{"a digit", "// there are 3 cases", "3"},
		{"a budget", "// fails past the 15-warning budget", "15"},
		{"a decimal", "// scales by 1.5x", "1"},
		{"an ordinal in digits", "// the 2nd pass rewrites", "2"},
		{"a cardinal word", "// there are three cases", "three"},
		{"a hyphenated word", "// twenty-five files", "twenty"},
		{"a capital word", "// Once the file lands", "Once"},
		{"a word ending a sentence", "// the analyzer runs once.", "once"},
		{"an ordinal word", "// the first pass", "first"},
		{"a ranked name", "// keeps the top-3 rows", "3"},
		{"a spaced encoding", "// decodes UTF-8", "8"},
		{"a version", "// present at otel v1.44.0", "44"},
		{"a block comment", "/* holds two entries */", "two"},
	} {
		t.Run(c.name, func(t *testing.T) {
			found := commentNumbers(c.text)
			require.Len(t, found, 1)
			assert.Equal(t, c.want, found[0].text)
			assert.Equal(t, c.want, c.text[found[0].offset:found[0].offset+len(c.want)])
		})
	}
}

// TestCommentNumbersLeavesNamesAlone pins the other side: a digit that belongs
// to a technical name, and a number word that belongs to an identifier, are
// what a comment has to be able to say.
func TestCommentNumbersLeavesNamesAlone(t *testing.T) {
	for _, c := range []struct {
		name string
		text string
	}{
		{"a hash", "// the sha256 of the payload"},
		{"an architecture", "// amd64 only"},
		{"a duration", "// waits 10ms for the ack"},
		{"a percentile", "// the p95 latency"},
		{"a major version suffix", "// example.com/mod/v2 resolves"},
		{"a url", "// see https://example.com/pull/419"},
		{"a qualified identifier", "// sync.Once guards the probe"},
		{"a package path", "// net/http serves it"},
		{"a camel case name", "// oneShot runs the probe"},
		{"a longer word", "// someone reads this later"},
		{"a format verb", "// %d formats the count"},
		{"prose with no number", "// the analyzer reports what it finds"},
	} {
		t.Run(c.name, func(t *testing.T) {
			assert.Empty(t, commentNumbers(c.text))
		})
	}
}

// TestCommentNumbersSeverityFollowsTheModule verifies the split the other
// comment-shape checks carry: an org module is bound by this convention and
// fails, and everybody else hears a warning.
func TestCommentNumbersSeverityFollowsTheModule(t *testing.T) {
	const src = `package main

// holds three entries
var m = map[string]int{}

func main() { _ = m }
`
	for _, c := range []struct {
		name        string
		module      *analysis.Module
		wantReports int
		wantWarns   int64
	}{
		{"org module fails", &analysis.Module{Path: "github.com/wow-look-at-my/go-toolchain"}, 1, 0},
		{"PazerOP module fails", &analysis.Module{Path: "github.com/PazerOP/tool"}, 1, 0},
		{"third-party module warns", &analysis.Module{Path: "example.com/consumer"}, 0, 1},
		{"nil module fails", nil, 1, 0},
	} {
		t.Run(c.name, func(t *testing.T) {
			resetCommentNumbersWarnings()
			logger.ResetWarnCount()
			t.Cleanup(logger.ResetWarnCount)
			before := logger.WarnCount()
			reports := runCommentNumbersOnSource(t, src, c.module)
			require.Len(t, reports, c.wantReports)
			assert.Equal(t, before+c.wantWarns, logger.WarnCount())
		})
	}
}

// TestCommentNumbersNamesTheRemedy pins that a finding quotes the number and
// says what to do instead, since the author has to rewrite the sentence.
func TestCommentNumbersNamesTheRemedy(t *testing.T) {
	reports := runCommentNumbersOnSource(t, "package main\n\n// runs the probe twice\nfunc main() {}\n", nil)
	require.Len(t, reports, 1)
	assert.Contains(t, reports[0].Message, `"twice" is a number in a comment`)
	assert.Contains(t, reports[0].Message, commentNumbersRemedy)
}

// TestCommentNumbersSkipsMachineText pins the comments that are not prose: a
// directive is read by a tool, and a generated file is written by a program.
func TestCommentNumbersSkipsMachineText(t *testing.T) {
	for _, c := range []struct {
		name string
		src  string
	}{
		{"a build tag", "//go:build linux && amd64\n\npackage main\n\nfunc main() {}\n"},
		{"a generate directive", "package main\n\n//go:generate stringer -type=Kind -linecomment=3\nfunc main() {}\n"},
		{"a generated file", "// Code generated by stringer. DO NOT EDIT.\n\npackage main\n\n// holds three entries\nfunc main() {}\n"},
	} {
		t.Run(c.name, func(t *testing.T) {
			assert.Empty(t, runCommentNumbersOnSource(t, c.src, nil))
		})
	}
}

// runCommentNumbersOnSource parses src and returns what the analyzer reports.
// No type information is needed: the check reads comments.
func runCommentNumbersOnSource(t *testing.T, src string, module *analysis.Module) []analysis.Diagnostic {
	t.Helper()
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, "/consumer/main.go", src, parser.ParseComments)
	require.NoError(t, err)

	var reports []analysis.Diagnostic
	pass := &analysis.Pass{
		Analyzer: CommentNumbersAnalyzer,
		Fset:     fset,
		Files:    []*ast.File{file},
		Report:   func(d analysis.Diagnostic) { reports = append(reports, d) },
		Module:   module,
	}
	_, err = runCommentNumbers(pass)
	require.NoError(t, err)
	return reports
}
