package vet

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestRunGofmtClean(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "main.go"), `package main

func main() {
	println("hello")
}
`)
	chdir(t, dir)

	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.NoError(t, ed.Err())
}

func TestRunGofmtDetectsUnformatted(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "main.go"), "package main\nfunc main(){println(\"hello\")}\n")
	chdir(t, dir)

	// In check mode RunGofmt itself no longer errors; the unformatted file is
	// recorded as a violation on the editor and never rewritten.
	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.Error(t, ed.Err())
	assert.Contains(t, ed.Err().Error(), "main.go")
}

func TestRunGofmtFix(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "main.go")
	writeFile(t, path, "package main\nfunc main(){println(\"hello\")}\n")
	chdir(t, dir)

	ed := NewEditor(true)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.True(t, changed)
	require.NoError(t, ed.Err())

	// Running again should find nothing to fix.
	ed2 := NewEditor(false)
	changed2, err2 := RunGofmt(ed2)
	require.NoError(t, err2)
	assert.False(t, changed2)
	require.NoError(t, ed2.Err())
}

func TestRunGofmtSkipsVendor(t *testing.T) {
	dir := t.TempDir()
	vendorDir := filepath.Join(dir, "vendor")
	require.NoError(t, os.MkdirAll(vendorDir, 0o755))
	writeFile(t, filepath.Join(vendorDir, "bad.go"), "package bad\nfunc f(){}\n")
	chdir(t, dir)

	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.NoError(t, ed.Err())
}

func TestRunGofmtSkipsTestdata(t *testing.T) {
	dir := t.TempDir()
	tdDir := filepath.Join(dir, "testdata")
	require.NoError(t, os.MkdirAll(tdDir, 0o755))
	writeFile(t, filepath.Join(tdDir, "bad.go"), "package bad\nfunc f(){}\n")
	chdir(t, dir)

	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.NoError(t, ed.Err())
}

func TestRunGofmtSkipsGeneratedFiles(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "generated.go")
	content := "// Code generated by test. DO NOT EDIT.\n\npackage main\nfunc f(){println(\"generated\")}\n"
	writeFile(t, path, content)
	chdir(t, dir)

	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.NoError(t, ed.Err())

	changed, err = RunGofmt(NewEditor(true))
	require.NoError(t, err)
	assert.False(t, changed)

	got, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Equal(t, content, string(got))
}

func TestRunGofmtSkipsUnparseable(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, filepath.Join(dir, "broken.go"), "package main\nfunc ({\n")
	chdir(t, dir)

	// Should not return an error for parse failures — go vet covers those.
	ed := NewEditor(false)
	_, err := RunGofmt(ed)
	require.NoError(t, err)
	require.NoError(t, ed.Err())
}

func TestRunGofmtEmptyDir(t *testing.T) {
	dir := t.TempDir()
	chdir(t, dir)

	ed := NewEditor(false)
	changed, err := RunGofmt(ed)
	require.NoError(t, err)
	assert.False(t, changed)
	require.NoError(t, ed.Err())
}

// helpers

func writeFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

func chdir(t *testing.T, dir string) {
	t.Helper()
	old, _ := os.Getwd()
	require.NoError(t, os.Chdir(dir))
	t.Cleanup(func() { os.Chdir(old) })
}
