//go:build go1.19
// +build go1.19

// Code generated by go-toolchain. DO NOT EDIT.
//
// go-toolchain injects this file into every main package it builds. On startup
// it reads the process's cgroup memory limit (cgroup v2 or v1) and, unless a
// limit is already configured, calls runtime/debug.SetMemoryLimit with a
// fraction of that limit. This keeps the Go garbage collector under the
// container's memory ceiling instead of letting the heap grow until the kernel
// OOM-kills the process.
//
// Runtime knobs (read when the program starts, not at build time):
//
//	GOMEMLIMIT                   If set to anything, this guard does nothing and
//	                             Go's own handling wins. GOMEMLIMIT=off is the
//	                             per-deployment kill switch.
//	GO_TOOLCHAIN_MEMLIMIT_RATIO  Overrides the default 0.9 ratio, e.g. "0.8".
//	                             "off" (or 0/false/no) disables the guard.
//
// The code is stdlib-only and a no-op when no cgroup memory limit is found,
// including on non-Linux systems where the cgroup files do not exist. All
// identifiers are prefixed so they cannot collide with the host package, and
// init never panics: any unexpected error simply leaves the limit untouched.

package main

import (
	"os"
	"path/filepath"
	"runtime/debug"
	"strconv"
	"strings"
)

func init() {
	// Tuning the GC must never crash the program it is meant to protect.
	defer func() { _ = recover() }()

	// Defer to an explicit GOMEMLIMIT (a real value, or "off" to opt out).
	if _, ok := os.LookupEnv("GOMEMLIMIT"); ok {
		return
	}

	const gtmlMaxInt64 = 1<<63 - 1

	// If a limit is already in effect (set by other init code), leave it alone.
	if debug.SetMemoryLimit(-1) != gtmlMaxInt64 {
		return
	}

	ratio := 0.9
	if v, ok := os.LookupEnv("GO_TOOLCHAIN_MEMLIMIT_RATIO"); ok {
		switch strings.ToLower(strings.TrimSpace(v)) {
		case "", "off", "0", "false", "no":
			return
		}
		r, err := strconv.ParseFloat(strings.TrimSpace(v), 64)
		if err != nil || r <= 0 || r > 1 {
			return
		}
		ratio = r
	}

	limit, ok := gtmlCgroupMemoryLimit("/")
	if !ok || limit == 0 {
		return
	}

	capped := uint64(float64(limit) * ratio)
	if capped > gtmlMaxInt64 {
		capped = gtmlMaxInt64
	}
	if capped == 0 {
		return
	}
	debug.SetMemoryLimit(int64(capped))
}

// gtmlCgroupMemoryLimit returns the cgroup memory limit in bytes for the current
// process, or ok=false when there is no finite limit. root is the filesystem
// root to read under ("/" in production; a fixture directory under test).
func gtmlCgroupMemoryLimit(root string) (uint64, bool) {
	mountsRaw, ok := gtmlReadFile(filepath.Join(root, "proc", "self", "mountinfo"))
	if !ok {
		return 0, false
	}
	cgroupRaw, ok := gtmlReadFile(filepath.Join(root, "proc", "self", "cgroup"))
	if !ok {
		return 0, false
	}
	mounts := gtmlParseMounts(mountsRaw)
	cgroups := gtmlParseCgroups(cgroupRaw)

	// cgroup v2: a single unified hierarchy line "0::<path>" and a cgroup2 mount.
	if rel, ok := gtmlV2RelPath(cgroups); ok {
		if mRoot, mPoint, ok := gtmlFindCgroup2Mount(mounts); ok {
			if path, ok := gtmlResolve(mPoint, mRoot, rel); ok {
				if limit, ok := gtmlV2Limit(root, path, mPoint); ok {
					return limit, true
				}
			}
		}
	}

	// cgroup v1: the hierarchy line whose controller list contains "memory".
	if rel, ok := gtmlV1RelPath(cgroups); ok {
		if mRoot, mPoint, ok := gtmlFindCgroupV1MemoryMount(mounts); ok {
			if path, ok := gtmlResolve(mPoint, mRoot, rel); ok {
				if limit, ok := gtmlV1Limit(root, path); ok {
					return limit, true
				}
			}
		}
	}

	return 0, false
}

func gtmlReadFile(path string) (string, bool) {
	b, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return string(b), true
}

type gtmlMountInfo struct {
	mountRoot  string
	mountPoint string
	fsType     string
	superOpts  string
}

// gtmlParseMounts parses /proc/self/mountinfo lines. Each line has the form
// "<id> <pid> <maj:min> <root> <mountpoint> <opts> [optional...] - <fstype> <source> <superopts>".
func gtmlParseMounts(content string) []gtmlMountInfo {
	var out []gtmlMountInfo
	for _, line := range strings.Split(content, "\n") {
		if line == "" {
			continue
		}
		sep := strings.SplitN(line, " - ", 2)
		if len(sep) != 2 {
			continue
		}
		pre := strings.Fields(sep[0])
		post := strings.SplitN(sep[1], " ", 3)
		if len(pre) < 5 || len(post) < 3 {
			continue
		}
		out = append(out, gtmlMountInfo{
			mountRoot:  pre[3],
			mountPoint: pre[4],
			fsType:     post[0],
			superOpts:  post[2],
		})
	}
	return out
}

type gtmlCgroupLine struct {
	id          string
	controllers string
	path        string
}

// gtmlParseCgroups parses /proc/self/cgroup lines of the form
// "<hierarchy-id>:<controller-list>:<cgroup-path>".
func gtmlParseCgroups(content string) []gtmlCgroupLine {
	var out []gtmlCgroupLine
	for _, line := range strings.Split(content, "\n") {
		if line == "" {
			continue
		}
		f := strings.SplitN(line, ":", 3)
		if len(f) != 3 {
			continue
		}
		out = append(out, gtmlCgroupLine{id: f[0], controllers: f[1], path: f[2]})
	}
	return out
}

func gtmlV2RelPath(lines []gtmlCgroupLine) (string, bool) {
	for _, l := range lines {
		if l.id == "0" && l.controllers == "" {
			return l.path, true
		}
	}
	return "", false
}

func gtmlV1RelPath(lines []gtmlCgroupLine) (string, bool) {
	for _, l := range lines {
		for _, c := range strings.Split(l.controllers, ",") {
			if c == "memory" {
				return l.path, true
			}
		}
	}
	return "", false
}

func gtmlFindCgroup2Mount(mounts []gtmlMountInfo) (root, mountPoint string, ok bool) {
	for _, m := range mounts {
		if m.fsType == "cgroup2" {
			return m.mountRoot, m.mountPoint, true
		}
	}
	return "", "", false
}

func gtmlFindCgroupV1MemoryMount(mounts []gtmlMountInfo) (root, mountPoint string, ok bool) {
	for _, m := range mounts {
		if m.fsType != "cgroup" {
			continue
		}
		for _, o := range strings.Split(m.superOpts, ",") {
			if o == "memory" {
				return m.mountRoot, m.mountPoint, true
			}
		}
	}
	return "", "", false
}

// gtmlResolve maps the cgroup path from /proc/self/cgroup (relative to the mount
// root) onto the actual mount point.
func gtmlResolve(mountPoint, mountRoot, cgroupPath string) (string, bool) {
	rel, err := filepath.Rel(mountRoot, cgroupPath)
	if err != nil {
		return "", false
	}
	if rel == "." {
		return mountPoint, true
	}
	if strings.HasPrefix(rel, "..") {
		return "", false
	}
	return filepath.Join(mountPoint, rel), true
}

// gtmlV2Limit walks up the cgroup v2 hierarchy from path to mountPoint and
// returns the smallest finite memory.max value found.
func gtmlV2Limit(root, path, mountPoint string) (uint64, bool) {
	const gtmlMaxUint64 = ^uint64(0)
	found := false
	smallest := gtmlMaxUint64
	cur := path
	for {
		if v, ok := gtmlReadV2Max(filepath.Join(root, cur, "memory.max")); ok {
			found = true
			if v < smallest {
				smallest = v
			}
		}
		if cur == mountPoint {
			break
		}
		parent := filepath.Dir(cur)
		if parent == cur {
			break
		}
		cur = parent
	}
	if !found {
		return 0, false
	}
	return smallest, true
}

func gtmlReadV2Max(path string) (uint64, bool) {
	s, ok := gtmlReadFile(path)
	if !ok {
		return 0, false
	}
	s = strings.TrimSpace(s)
	if s == "" || s == "max" {
		return 0, false
	}
	n, err := strconv.ParseUint(s, 10, 64)
	if err != nil {
		return 0, false
	}
	return n, true
}

// gtmlV1Limit returns the effective cgroup v1 memory limit: the smallest finite
// value among hierarchical_memory_limit (memory.stat) and memory.limit_in_bytes.
// A value at or above the page-aligned int64 max means "no limit".
func gtmlV1Limit(root, path string) (uint64, bool) {
	hml := gtmlHierarchicalLimit(filepath.Join(root, path, "memory.stat"))

	lib := uint64(0)
	if s, ok := gtmlReadFile(filepath.Join(root, path, "memory.limit_in_bytes")); ok {
		if n, err := strconv.ParseUint(strings.TrimSpace(s), 10, 64); err == nil {
			lib = n
		}
	}

	limit := uint64(0)
	have := false
	if hml != 0 {
		limit, have = hml, true
	}
	if lib != 0 && (!have || lib < limit) {
		limit, have = lib, true
	}
	if !have || limit >= gtmlV1NoLimitSentinel() {
		return 0, false
	}
	return limit, true
}

func gtmlHierarchicalLimit(path string) uint64 {
	s, ok := gtmlReadFile(path)
	if !ok {
		return 0
	}
	for _, line := range strings.Split(s, "\n") {
		f := strings.Fields(line)
		if len(f) == 2 && f[0] == "hierarchical_memory_limit" {
			if n, err := strconv.ParseUint(f[1], 10, 64); err == nil {
				return n
			}
			return 0
		}
	}
	return 0
}

// gtmlV1NoLimitSentinel is the value cgroup v1 uses to mean "unlimited":
// the largest int64 rounded down to a multiple of the page size.
func gtmlV1NoLimitSentinel() uint64 {
	const gtmlMaxInt64 = uint64(1<<63 - 1)
	ps := uint64(os.Getpagesize())
	if ps == 0 {
		return gtmlMaxInt64
	}
	return gtmlMaxInt64 / ps * ps
}
